version: "3"
services:
  naima:
    build: ./.
    user: gradle
    env_file: .env
  # See https://www.mongodb.com/compatibility/docker
  mongodb:
    image: mongo:5.0
    env_file: .env
    volumes:
      # Make mongo data persist after docker container is destroyed
      - ./db:/data/db
    ports:
      - 27017:27017
